spring:
  application.name: mimimimetr
  profiles.default: dev
  jpa:
    open-in-view: false
  datasource.driver-class-name: org.postgresql.Driver
server.port: 8080

---
spring:
  config.activate.on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  image-source: ${IMAGE_SOURCE}

logging:
  level:
    liquibase.executor: debug
    root: info
